#! /usr/bin/env python
# -*- coding: utf-8 -*-
from snakemake.utils import min_version
from snakemake.exceptions import WorkflowError
import os
import pandas as pd
#import json

min_version("6.4.1")

configfile: "config/config.yaml"

wildcard_constraints:
    runid = r"SRR\d+"

include: "rules/common.smk"
include: "rules/download_sra.smk"
include: "rules/align_multi_star.smk"
include: "rules/telescope.smk"
include: "rules/dataset.smk"

localrules: all

#rule all:
#    input:
#        expand('results/telescope/{sampid}/report.tsv', sampid=meta_table.index.to_list())

rule all:
    input:
        'results/dataset/counts.rds',
        'results/dataset/features.rds'


